### ISSUE TITLE
Persistant Arch Linux on a USB stick (BIOS)

### ISSUE THREAD

**Issue by Pincoffin** [KLINGTdotNET/klingt.net#1]
First of all, Thank you for a great tutorial, it works great, I have only one question, I would like to make it an encrypted intall. How would I go about that?

If I use the :

cryptsetup --verbose --cipher aes-xts-plain64 --key-size 512 --hash sha512 --iter-time 5000 --use-random luksFormat /dev/sdb2

i get an error that a 'block device required'

basically what I am wanting is the same setup as your tutorial but the main partiton encrypted

Im a bit of a newbie with Linux but learning as fast as I can, any help you can give would be greatly appreciated

**Comment by klingtnet** [comment]
I've made an encrypted USB Arch installation as well, but I didn't wrote a new article because of laziness :sleeping:
The Arch wiki has a nice page about [dm-crypt](https://wiki.archlinux.org/index.php/Dm-crypt/Device_encryption), that's also what I used to setup my installation. There is no need to use `sha512`, if you're curious about performance run the builtin benchmark `cryptsetup benchmark`. Sha-1 is secure enough.
Did you double check the path of the block device (`/dev/sdb2`)? You can list all block devices using `lsblk`.
The steps to setup a LUKS partition with ext4 look like this:
- `cryptsetup luksFormat --cipher=aes-xts-plain64 --key-size=256 --hash=sha1 --verify-passphrase /dev/sdX`
  - password will be **cropped** after hashing to the given key-size
  - defaults can be viewed using `cryptsetup --help`
- `cryptsetup luksUUID /dev/sdX` or get device name from the UUID using `findfs`
- `cryptsetup luksOpen $(findfs UUID=ABCDEFG) mappedDeviceName`
- `mkfs.ext4 -L someLabel /dev/mapper/mappedDeviceName`

Finally you've to edit your `/etc/crypttab` and `/etc/fstab` to automount the partition on boot (will ask for the passphrase).

I hope this helps.

**Comment by benben** [comment]
:+1:
