### ISSUE TITLE
Docker image for Prosody makes things easier

### ISSUE THREAD

**Issue by mark-kubacki** [KLINGTdotNET/klingt.net#2]
Hey Andreas!
This is about https://github.com/klingtnet/klingt.net/blob/1930eed642e955bfb330e0a740a33d84688d0f52/klingt.net/posts/run-you-own-jabber-server.rst

First, allow me to be shameless enough to link to one of my works: https://hub.docker.com/r/wmark/prosody/

Running _Prosody_ under Docker makes things easier for new users, which I believe is the target audience of your article. Worth mentioning it?

The aforementioned image supports RSA and ECDSA, and incorporates (my) **lua-pbkdf2** because unlike the built-in one this hash enables you to later synchronize _Prosody_ with an array of different other products (such as, but not limited to, the inferior **Discourse**). Its (the image's) lua-sec is build with BoringSSL, and I so happen to occasionally file bug reports and feature requests for both.

https://boringssl.googlesource.com/boringssl/+/2cac3506faf57f4e77d644e5ec0b13dc5d484691
https://github.com/brunoos/luasec/pull/47/files

**Comment by klingtnet** [comment]
Hi Mark,

thank you for the response. The target audience for the article are beginners, that's right. I have to admit that I don't maintain my prosody docker image anymore because I've switched back to a hosted service. Be it `ejabberd` or `prosody` the state of XMPP servers is a mess. I would like to have a single binary server (maybe written in go or Rust) that doesn't have the dependency hell that comes with one of the before mentioned ones. I could write my own, but I've enough to do with other projects at the moment.

Nevertheless, I will add a note about your prosody docker image in the article because it seems that you've taken a bit more thought in security than I did. Updating the article could take a while because I'm rebuilding my website.
